### ISSUE TITLE
UNABLE TO JOIN TO MY WORLD :(

### ISSUE THREAD

**Issue by matesaman9910** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#134]
Hi, when I join my aternos server I am stuck at loading terrain error and in the console, it just says that it can't load a lot of chunks because I am in them ??? 

so here is the Aternos console link: [https://mclo.gs/KhjjpIm]

and an example:

[Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

[Server thread/WARN] [FML]: HBM's Nuclear Tech Mod loaded a new chunk [1532, 2152] in dimension 0 (overworld) while populating chunk [1533, 2152], causing cascading worldgen lag.

here is a list of mods I use:

![image](https://github.com/TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT/assets/100013611/629430bb-8ec9-4f8d-8bff-72ffb99e99ec)

If you need any more info please ask me because I want to play on my server and I am willing to provide most of the information I know
Thanks for the help in advance and I hope to hear from some of you soon!
-matesaman9910

**Comment by matesaman9910** [comment]
Unfortunately, I noticed several issues with this type and no fixed issues, so I am deleting the server. It is disappointing that the mode creator cannot resolve any issues.

**Comment by NetherGonnaGiveUp** [comment]
I think the mod dev tripping balls and dropped this project, a bit sad unless there's other volunteer naintainer
