### ISSUE TITLE
Geyser water entities save, causing particles to get stuck in unloaded chunks which make servers lag and games freeze up.

### ISSUE THREAD

**Issue by Spookysaw** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#14]
A problem fixed in the 1.7.10 version [here](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/releases/tag/1.0.27X4011). Once a geyser is loaded then unloaded for awhile, it will accumulate particles, meaning when they are next loaded by any player their game will freeze. This also makes the server's TPS drop by 10 at the least. This does not seem to happen with the smaller chlorine geysers.

**Comment by TheOriginalGolem** [comment]
I'll look into this

**Comment by TheOriginalGolem** [comment]
Fixed now
