### ISSUE TITLE
Compatibility with Biomes-o-Plenty or other worldgen mods. 

### ISSUE THREAD

**Issue by DNIWE041** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#22]
The HBM NTM doesn't have structure generation compatibility with any world gen mod who adds new biomes because almost all structures hard lock to biome type, like abandoned power plant spawns only in desert (or maybe with very rare chance in mountain biome but i didn't find any for 100 hours gameplay).
Maybe you can add a config option to disable this hard lock, or add compatibility for few popular worldgen mods like Biomes-o-Plenty?

**Comment by Alcatergit** [comment]
It will be fixed in the update i am working on.

**Comment by TheOriginalGolem** [comment]
Closing as it has been fixed
