### ISSUE TITLE
[AUDIO] Centrifuges keep making noise even after done with a process.

### ISSUE THREAD

**Issue by Vetpetmon** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#25]
Once a centrifuge finishes its processes, the audio may continue to loop. Seems to happen between _chunkloads_.

First noted in [hbm-1.6.5a-Gv2](https://github.com/TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT/releases/tag/hbm-1.6.5a-Gv2)

Potential fix: run a check each time the centrifuge is loaded, if it is not processing any input, stop the audio loop.

Additional notes: Why can I hear my 4 centrifuges running from 6 chunks away?

**Comment by TheOriginalGolem** [comment]
Can't replicate

**Comment by Vetpetmon** [comment]
I should've added that unloading and re-loading centrifuges cause audio loop bugs. It also just plays loudly. Then again, this was for 1.6.5a-Gv2, so perhaps that is fixed now.
