### ISSUE TITLE
Wrong recipe for Desh Blend

### ISSUE THREAD

**Issue by SzerGRA** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#28]
In the recipe for desh blend Boron is replaced with Actinium which is wrong.
![Screenshot 1 7 10 ](https://user-images.githubusercontent.com/79095633/198983538-0b347979-c9f6-4c6c-b3ea-f641bb6aadaf.jpg)
![Screenshot 1 12 2  2](https://user-images.githubusercontent.com/79095633/198983543-9e5f9d3c-5eb6-4ac9-bbdb-8812f9a944b2.jpg)

**Comment by TheOriginalGolem** [comment]
It probably was updated at some point. Will update it when I get a chance.

**Comment by TheOriginalGolem** [comment]
Will be in the next update
