### ISSUE TITLE
Add OpenComputers support

### ISSUE THREAD

**Issue by Renno231** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#29]

**Comment by TheOriginalGolem** [comment]
Its coming but its gonna take some time

**Comment by TheOriginalGolem** [comment]
Making good progress with that, will probably be in 1.7.1a

**Comment by MrMunchkin21** [comment]
I know that this is a long shot, though is there any updates on a time frame?

HBM is easily one of my favorite mods and I am getting more addicted to OpenComputers by the day. Though I would love to be able to integrate them together to have the likes of the radar display onto an OpenComputers screen or use OpenComputers to designate a target area for nukes.

**Comment by TheOriginalGolem** [comment]
Added in new update
