### ISSUE TITLE
1.12.2 server "cascading worldgen lag"

### ISSUE THREAD

**Issue by makaooo1** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#31]
Hi I have a problem, im experiencing quite a bit of lag in form of freezes between 2-5 sec, log says:

 [00:34:12] [Server thread/WARN] [FML]: HBM's Nuclear Tech Mod loaded a new chunk [-165, -457] in dimension 0 (overworld) while populating chunk [-164, -457], causing cascading worldgen lag.

It would seem the mod starts loading chunks from the middle of the world, on line 1687 it starts it and keeps going.
Here is my servers log: https://mclo.gs/9jSaBlt

Im also running a quite bit of mods so those could also contribute to the problem but the log says its HBM.

Tested with just HBM and didnt notice any lag, I flew around in creative little over 10mins. Log still shows constantly the same cascading worldgen lag message

Here is the HBM only server log: https://mclo.gs/xZfmJfB

Im also running millenair,  biomes o plenty, mekanism and other tech mods, few other light mods( backbacks etc.) that also might contribute to the problem.

Im running my server on exaroton with 16gb of ram.
HBM mod version: hbm-1.6.9a-G

**Comment by TheOriginalGolem** [comment]
Not an issue
