### ISSUE TITLE
dfc emmiter not working and blowing up

### ISSUE THREAD

**Issue by TheMgfeedthebeast** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#33]
hello i made a server for me and a friend and we made a dfc reactor, but the emitters won't save values and when i turn them on they will just blow up. tried many designs and they wont work if you need screenshots please let me know

**Comment by firefoxyz** [comment]
are you using 1.6.9a-G?

**Comment by TheMgfeedthebeast** [comment]
yep

**Comment by TheMgfeedthebeast** [comment]
yep i am

**Comment by firefoxyz** [comment]
well 1.6.9 is still alpha so there is bugs, 1.6.8-gv5 doesn't have this issue. i would recommend using 1.6.8 until the issue is fixed

**Comment by TheMgfeedthebeast** [comment]
hey thank you i wil test it soon

**Comment by TheMgfeedthebeast** [comment]
i will have the issue open until the issue is gone if that's fine if not you can close it

**Comment by TheOriginalGolem** [comment]
> hey thank you i will test it soon

Please let me know if 1.6.8 works for you

**Comment by TheMgfeedthebeast** [comment]
seems like it works but is stuck at 0 on the emitters

**Comment by TheOriginalGolem** [comment]
Could not replicate
