### ISSUE TITLE
Any door doesn't protect against radiation.

### ISSUE THREAD

**Issue by DNIWE041** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#36]
So, the problem written in title.
No one door in mod can protect your home against radiation. 
I think it's happen because 'door tile' ('tech block' who replacing space in door when you close it) dont have rad-resist. And if you want to build bunker you need to use vanilla doors maked from pistons and concrete bricks.
For example high-tech blast protect door on screenshot doesnt have any radiation resistance (im looking at this 'tech block'). I think its be a good thing if you make this doors more usable. Not for all doors of cource, because some doors named as fire-resistant and etc. But the blast-protected doors, or QE containment door looks like they can protect your home from radiation.
Sorry for grammaticus errors, english is not my main language.
![image](https://user-images.githubusercontent.com/76884831/202844274-a2b13f93-85e5-43b1-810b-4d8f3a555d8f.png)

**Comment by TheOriginalGolem** [comment]
will look into it

**Comment by Alcatergit** [comment]
I fixed that a while ago in my fork. Will roll out soon.

**Comment by TheOriginalGolem** [comment]
Closing as it has been fixed
