### ISSUE TITLE
All mod blocks switched when attempting to play on modded world with other mods.

### ISSUE THREAD

**Issue by ShepoPL** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#40]
When I try to play on modded world with other mods "level.dat backup is being used" message pops out and after clicking yes world loads with all mod blocks switched with other blocks. Tested with multiple mods - problem still occurs.

**Comment by TheOriginalGolem** [comment]
Its an id shift, this happens sometimes, nothing I can do

**Comment by ShepoPL** [comment]
Is it possible to change id's by myself? Where is id's file located?
