### ISSUE TITLE
Your commit history is horrible

### ISSUE THREAD

**Issue by spikespaz** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#52]
I wanted to fix a bug, so I tried bisecting but I can't even find what commit `1.8.1a-Gv2` corresponds to.

I'd be a good contributor to have sending code, but I can't help if your VCS is a nightmare. Please tag your releases and faithfully update the version specifier. It would help newcomers to the project contribute and navigate code changes. I'm sure I'm not the only person turned away by your chaos.

And merge commits are bad. Learn to use git rebase? And make your commit messages actually meaningful? Please???

**Comment by TheOriginalGolem** [comment]
Hey sorry for the late reply, I currently don't have electricity so i can only reply periodicly. Yes I agree the recent commit history is a mess, also i did not know merge commits were bad, still relatively new to using git. Do you still want to know which commit corresponds to 1.8.1-Gv2? Again, sorry about the mess of a commit history.

**Comment by TheOriginalGolem** [comment]
Also yes I probably should make git messages a bit more clear.

**Comment by spikespaz** [comment]
Yes, I'd like to know which commit corresponds to Gv2 and Gv3. My friend complained that pipes seemed to be working differently, and that some items lost their crafting recipe between the two versions. There was lots of code change I presume so I was going to diff the two commits. I tried hunting through history but there are several commits that are rather large and nondescript. I'm sorry if I was rude with my wording. I hope you are doing well and can continue to enjoy programming even without electricity.

**Comment by TheOriginalGolem** [comment]
Gv2 is all the commits up till here: https://github.com/TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT/commit/01f4ca26d499dc7477ab33b85fe6dc460b1e293c

Gv3 is all the commits up till here: https://github.com/TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT/commit/f6b6591c3d13a3b68bd331bcda5c078ed632d56c

Each new release has a version bump commit if that helps.
