### ISSUE TITLE
The Firebox and Steel Furnace sometimes crash when shift-clicking items

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#56]
In the modpack I'm playing I've never had a crash since months until testing the firebox and steel furnace. Both occasionally crash when shift-clicking items into the machines.

Crashlog link:
https://paste.ee/p/sAcmL

**Comment by TheOriginalGolem** [comment]
Will be fixed in the update later today.

**Comment by TheOriginalGolem** [comment]
Fixed in newest version
