### ISSUE TITLE
RBMK Crane and Consol disappear after save and reload

### ISSUE THREAD

**Issue by Njet75** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#64]
RBMK Crane and Consol disappear after save and reload.
The consol still there but invisible.When i relink with linking tool it appear again.
This issue is fixed in Hbm's Nuclear Tech - Alcater Edition but still exist in latest hbm-1.8.2aGv2

![console 1](https://user-images.githubusercontent.com/8996171/210219802-6ff80949-57b3-42e3-a65d-fc6f2cc8df44.png)
![console2](https://user-images.githubusercontent.com/8996171/210219808-09ae950f-e813-4df9-b5c0-b69b1c82077b.png)

/Michael

**Comment by TheOriginalGolem** [comment]
Will look into it

**Comment by TheOriginalGolem** [comment]
Might be fixed in new update, if its not, reopen the issue
