### ISSUE TITLE
Crash after firing a weapon from HBM

### ISSUE THREAD

**Issue by KaxelOleg** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#70]
Triggered if you fire a weapon at a shield from the Spartan Shield mod with enchantment prongs.When I used the shield without this enchantment, everything was fine. This enchantment deals damage to the one who hits the player who is currently using the block, and if you shoot from a regular bow, the shooter will receive damage
UPD:
We checked on other mods, in Immersive Engineering, the same thing happens when a railgun is fired, the server crashes, apparently the problem is already in the enchantment itself

**Comment by TheOriginalGolem** [comment]
Bug with whatever mod adds enchantment prongs

**Comment by TheOriginalGolem** [comment]
Not fixing as its not a ntm issue
