### ISSUE TITLE
Advanced shredder blades are made from the same, advanced shredder blades

### ISSUE THREAD

**Issue by KaxelOleg** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#72]
Because of this, they cannot be crafted

**Comment by Primum-Qualia** [comment]
yeah, this one was kind of annoying, as i ran into this bug as I was just about to make an ore acidizer lol.

**Comment by TheOriginalGolem** [comment]
Fixed in dev, when the next update is out it'll be fixed.
