### ISSUE TITLE
Do conveyor belts exist?

### ISSUE THREAD

**Issue by spikespaz** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#81]
The large open ports with the arrows on the machines look like they're made for conveyor belts, and I have seen conveyor belts in screenshots of the original mod.

Did they not make it into the port?

I can't figure out how to insert Niter into the Chemical Plant.

**Comment by TheOriginalGolem** [comment]
No, conveyors have not been implemented yet, we are currently focused at the moment with desperately needed optimisation, so newer 1.7 features will take a bit of time. The ports on the side allow the machines to auto grab resources from containers place in front of them, also works with other mods item pipes (e.g. Mekanism). Also what recipe are you making?

**Comment by spikespaz** [comment]
Just coolant, I'm trying to get it to extract from either an enderio item buffer, or a vanilla chest, or one of your storage crates. None of these things work.

**Comment by TheOriginalGolem** [comment]
Huh, weird, I'll have a look when I get home and see what is going on
