### ISSUE TITLE
Issue with spongeforge and nuclear tech mod

### ISSUE THREAD

**Issue by DukeTheBadDragon** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#83]
![Console](https://user-images.githubusercontent.com/123263124/213882484-fb55adee-2a15-40ef-b64f-7bf411eb2d80.png)

Wondering if there is a fix for it. I cant take out sponge forge or else i cant use my plugins. This is not a crash but this error keeps being spammed in the console,

**Comment by TheOriginalGolem** [comment]
Spongeforge and any other 3rd party server software is not supported
