### ISSUE TITLE
Solar tower's mirror light rays cause significant lag

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#85]
Looking at the rays of light for the solar tower mirror (especially when building large arrays) drops FPS significantly for some reason.

Is there any option to disable the rays? Otherwise can a config be added?

**Comment by TheOriginalGolem** [comment]
set enableShaders2 to false in the config, a better solution will eventually come
