### ISSUE TITLE
OpenGL Error: 1282 (Invalid Operation)

### ISSUE THREAD

**Issue by C7bor9** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#92]
Hello
I have a problem, my screen is very weird:

![image](https://user-images.githubusercontent.com/125082504/218176995-3f5c7082-0f76-4c50-9c66-52bcd9b73165.png)

I have 
- 1.12.2-4.16.1.301
- hbm-1.8.2a-Gv2
- OptiFine_1.12.2_HD_U_F5
In my mods file.

[latest.log](https://github.com/TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT/files/10710476/latest.log)

How can I solve this problem?

**Comment by DNIWE041** [comment]
Update your video driver or try OptiFine_1.12.2_HD_U_G5 (not F5 version!).
Also disable fast render.

**Comment by Vetpetmon** [comment]
Try disabling Shaders2 if you haven't already

**Comment by TheOriginalGolem** [comment]
Optifine breaks the mod's custom shaders
